# Generated by Django 5.2 on 2026-01-08 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 8, 18, 44, 37, 226550, tzinfo=datetime.timezone.utc)),
        ),
    ]
