# Generated by Django 5.2 on 2026-01-08 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 8, 19, 26, 40, 899417, tzinfo=datetime.timezone.utc)),
        ),
    ]
